# Features - Groups of programs/packages/services that
#            can have additional configuration.
#
# Packages - Anything that is installed via the package
#            manager.
# 
# Programs - Anything program that requires additional
#            configuration. You may also need to specify
#            the package as well, if it is not a NixOS
#            option.
#
# Services - Basically the same as programs, just separated
#            out for (in)convenience.

# ----------------
# --  FEATURES  --
# ----------------
[features.desktop]
programs = [
  "firefox",
  "ghostty",
  "vscode",
]

packages = [
  # Applications
  "thunderbird",
  "slack"
]

[features.desktop-darwin]
programs = [
  "firefox",
  "vesktop",
  "vscode",
]

packages = [
  "slack"
]

[features.developer]
programs = ["git"]
packages = ["asdf-vm"]

[features.gaming]
programs = [
  "steam",
  "vesktop"
]

packages = []

[features.laptop]
packages = []

[features.fonts]
packages = []

# ---------------
# --   HOSTS   --
# ---------------
[hosts.magnezone] # personal nixos laptop
class = "nixos"
homeConfig = true
personal = true

features = [
  "desktop",
  "laptop",
  "developer",
  "gaming"
]

programs = []

services = [
  "fonts",
  "sshAgent"
]

[hosts.magnezone.plasma]
launcherIcon = "nix-snowflake"

[hosts.Archen] # personal macbook pro
class = "darwin"
homeConfig = true
personal = true

features = [
  "developer",
  "desktop-darwin"
]

programs = [
  "iterm"
]

packages = [
  "sshpass",
  "ffmpeg_7",
  "yt-dlp",
  "doctl"
]

[hosts.duosion] # personal cachyos desktop
class = "standalone"
homeConfig = true
personal = true

features = [
  "desktop",
  "developer",
  "gaming"
]

programs = []
services = ["fonts"]
packages = []

[hosts.duosion.plasma]
launcherIcon = "org.cachyos.hello"

[hosts.tinkaton] # aur build server
class = "nixos"
homeConfig = true
personal = true

features = ["developer"]

services = ["nginx"]

packages = ["yay"]

