node.rules = [
	{
		matches = [
			{
				application.name="~.*RecordStream.*"
			}
		]
		actions = {
			update-props = {
				node.force-quantum = 1024
			}
		}
	},
	{
		matches = [
			{
				application.name="~.*Chromium.*"
			}
		]
		actions = {
			update-props = {
				node.force-quantum = 1024
			}
		}
	}
]
