node.rules = [
	{
		matches = [
			{
				application.name="~.*OBS.*"
			}
		]
		actions = {
			update-props = {
				node.force-quantum = 2048
			}
		}
	},
    {
		matches = [
			{
				application.name="~.*Firefox.*"
			}
		]
		actions = {
			update-props = {
				node.force-quantum = 2048
			}
		}
	}
]
