node.rules = [
    {
        matches = [
            {
                application.name = "~.*Firefox.*"
            }
        ]
        actions = {
            update-props = {
                target.object = "chatot-out-pc-2"
            }
        }
    },
    {
        matches = [
            {
                application.name = "~.*Chromium.*"
            }
        ]
        actions = {
            update-props = {
                target.object = "chatot-out-discord"
            }
        }
    } 
]