context.objects = [
    {   
        factory = adapter
        args = {
           factory.name     = support.null-audio-sink
           node.name        = "chatot-out-pc-1"
           node.description = "Chatot Out - PC 1"
           media.class      = Audio/Sink
           object.linger    = true
           audio.position   = [L R]
           monitor.channel-volumes = true
           monitor.passthrough = true
        }
    },
    {   
        factory = adapter
        args = {
           factory.name     = support.null-audio-sink
           node.name        = "chatot-out-pc-2"
           node.description = "Chatot Out - PC 2"
           media.class      = Audio/Sink
           object.linger    = true
           audio.position   = [L R]
           monitor.channel-volumes = true
           monitor.passthrough = true
        }
    },
    {   
        factory = adapter
        args = {
           factory.name     = support.null-audio-sink
           node.name        = "chatot-out-obs-monitor"
           node.description = "Chatot Out - OBS Monitoring"
           media.class      = Audio/Sink
           object.linger    = true
           audio.position   = [L R]
           monitor.channel-volumes = true
           monitor.passthrough = true
        }
    },
    {   
        factory = adapter
        args = {
           factory.name     = support.null-audio-sink
           node.name        = "chatot-out-discord"
           node.description = "Chatot Out - Discord"
           media.class      = Audio/Sink
           object.linger    = true
           audio.position   = [L R]
           monitor.channel-volumes = true
           monitor.passthrough = true
        }
    },
    {   
        factory = adapter
        args = {
           factory.name     = support.null-audio-sink
           node.name        = "chatot-in-mic"
           node.description = "Chatot In - Mic"
           media.class      = Audio/Source/Virtual
           object.linger    = true
           audio.position   = [L R]
           monitor.channel-volumes = true
           monitor.passthrough = true
        }
    },
    {   
        factory = adapter
        args = {
           factory.name     = support.null-audio-sink
           node.name        = "chatot-in-stream-mix"
           node.description = "Chatot In - Stream Mix"
           media.class      = Audio/Source/Virtual
           object.linger    = true
           audio.position   = [L R]
           monitor.channel-volumes = true
           monitor.passthrough = true
        }
    },
    {   
        factory = adapter
        args = {
           factory.name     = support.null-audio-sink
           node.name        = "chatot-in-vod-ignored"
           node.description = "Chatot In - VOD Ignored"
           media.class      = Audio/Source/Virtual
           object.linger    = true
           audio.position   = [L R]
           monitor.channel-volumes = true
           monitor.passthrough = true
        }
    },
]
