# context.properties {
#   default.clock.quantum = 2048
#   default.clock.min-quantum = 2048
# }

context.properties = {
  default.clock.quantum = 4096
  default.clock.min-quantum = 4096
  default.clock.max-quantum = 8192
  default.clock.quantum-limit = 8192
  clock.power-of-two-quantum = true
}

pulse.properties = {
  pulse.min.quantum = 4096/48000
}