# This maybe needs --cursor-sacle-height 2160
# Investigate more when playing something that isn't FFXIV
SCB_GAMESCOPE_ARGS="-f -w 3840 -h 2160 -W 3840 -H 2160 -r 239.98 --force-grab-cursor --hdr-enabled --hdr-itm-enable -O *,eDP-2"zz